# Generated by Django 2.2.12 on 2020-08-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.SmallIntegerField()),
                ('number2', models.SmallIntegerField()),
            ],
        ),
    ]
